name: Swift

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.0.3"
      - run: swift test -c release

  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.0.3"
      - run: swift test -c release
  
  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.0.2"
      - run: swift test -c release
