name: Swift

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  Xcode:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode.app
    steps:
      - uses: actions/checkout@v3
      - run: swift -version
      - run: swift test -c release -Xswiftc -enable-testing

  Linux:
    strategy:
      matrix:
        tag: ['5.9.1']
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v4
      - run: swift test -c release -Xswiftc -enable-testing
  
  Windows:
    strategy:
      matrix:
        tag: ['5.9.1']
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sushichop/gha-swift-env@v1
        with:
          swift-version: ${{ matrix.tag }}
      - run: swift test -c release -Xswiftc -enable-testing
